In [1]:
import numpy as np
import pandas as pd

In [11]:
arr = np.array([1,2,3,4,0])

In [12]:
arr.ndim , arr.size, arr.shape,arr.any()

(1, 5, (5,), np.True_)

In [14]:
arr.argmax()

np.int64(3)

In [ ]:
1. What is NumPy?

NumPy (Numerical Python) is a Python library used for numerical and scientific computing.
It provides fast array operations, mathematical functions, linear algebra, and

In [ ]:
2. What is a NumPy array?

A numpy.ndarray is a homogeneous, multidimensional, contiguous memory array** optimized for fast computations.

In [15]:
import numpy as np
arr = np.array([1, 2, 3])

In [16]:
arr

array([1, 2, 3])

In [ ]:
| Python List             | NumPy Array             |
| ----------------------- | ----------------------- |
| Stores mixed data types | Only same data type     |
| Slow operations         | Very fast (C optimized) |
| No vector operations    | Supports vectorization  |


In [17]:
5. How to create special arrays?
np.zeros((3,3))
np.ones((2,4))
np.arange(1,10,2)
np.linspace(0,1,5)



Object `arrays` not found.


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [1]:
import numpy as np
n = np.diagonal([[4,51]])

In [2]:
n

array([4])

In [26]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(np.diagonal(arr))


[1 5 9]


In [ ]:
6. What is vectorization?

Performing operations on entire arrays without loops.

In [ ]:
7. What is broadcasting in NumPy?

Broadcasting allows operations between arrays of different shapes.

In [27]:
arr.dtype

dtype('int64')

In [ ]:
12. How to change data type?

In [ ]:
arr.astype(float)

In [ ]:
Deep copy    :  Changes do NOT affect original

Shallow copy  : Changes affect original

In [ ]:
14. How to concatenate arrays?

In [ ]:
np.concatenate([a, b])
np.vstack([a, b])
np.hstack([a, b])


In [ ]:
16. What is axis in NumPy?

Axis defines direction:
axis=0 → columns
axis=1 → rows

In [ ]:
arr.sum(axis=0)  # column-wise sum


In [29]:
arr = np.array([[1,2,3,4],[4,5,6,7]])

In [32]:
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [31]:
arr.sum(axis=0)

array([ 5,  7,  9, 11])

In [33]:
arr.sum(axis=1)

array([10, 22])

In [ ]:
17. How to apply boolean indexing?

arr[arr > 5]

In [ ]:
np.where(arr > 10, 'Yes', 'No')

In [34]:
np.sort(arr)

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [ ]:
np.unique(arr)

In [35]:
a = np.array([1,2,3])
b = np.array([5,6,7])

In [36]:
np.dot(a, b)

np.int64(38)